name: K6 load teste
on: [push]
jobs:
  k6-load-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: run k6 load test
        uses: grafana/k6-action@v0.2.0
        with:
          filename: scripts/test.js

      # move o relatório para a pasta report
      - run: ls & mkdir report & mv index.html report

      - name: Upload k6 report
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: report
